import { defineNuxtPlugin } from "#app";
import PrimeVue from "primevue/config";
import Button from "primevue/button";
import Dialog from 'primevue/dialog';
import DataTable from 'primevue/datatable';
import Column from 'primevue/column';
import ColumnGroup from 'primevue/columngroup';
import InputText from 'primevue/inputtext'; //optional 
import Row from 'primevue/row';
import Textarea from 'primevue/textarea';
import FileUpload from 'primevue/fileupload';
import ToastService from 'primevue/toastservice';
import Toast from 'primevue/toast';
import ConfirmationService from 'primevue/confirmationservice';
import ConfirmDialog from 'primevue/confirmdialog';
export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.vueApp.use(PrimeVue, { ripple: true });
    nuxtApp.vueApp.component('Button', Button);
    nuxtApp.vueApp.component('Dialog', Dialog);
    nuxtApp.vueApp.component('DataTable', DataTable);
    nuxtApp.vueApp.component('Column', Column);
    nuxtApp.vueApp.component('ColumnGroup', ColumnGroup);
    nuxtApp.vueApp.component('Row', Row);
    nuxtApp.vueApp.component('InputText', InputText);
    nuxtApp.vueApp.component('Textarea', Textarea);
    nuxtApp.vueApp.component('FileUpload', FileUpload);
    nuxtApp.vueApp.use(ToastService);
    nuxtApp.vueApp.component('Toast', Toast);
    nuxtApp.vueApp.use(ConfirmationService);
    nuxtApp.vueApp.component('ConfirmDialog', ConfirmDialog);
});